:global:
  componentName: openshift4-operators
  githubUrl: https://github.com/appuio/component-openshift4-operators
  feature_goldenTests: true
  testMatrix:
    key: instance
    entries:
      - openshift-operators-redhat
      - openshift-operators

.github/workflows/test.yaml:
  goldenTest_makeTarget: golden-diff -e instance=${{ matrix.instance }}
  makeTarget: test -e instance=${{ matrix.instance }}

docs/antora.yml:
  name: openshift4-operators
  title: openshift4-operators

Makefile:
  includes:
    - Makefile.custom.mk
