= Parameters

The parent key for all of the following parameters is `openshift4_operators`.

== `namespace`

[horizontal]
type:: string
default:: `${_instance}`

The namespace to create for the component instance.
The component is implemented in such a way that only instances (and therefore namespaces) `openshift-operators` and `openshift-operators-redhat` can be created.
Generally, it shouldn't be necessary to override this parameter.

== `defaultInstallPlanApproval`

[horizontal]
type:: string
default:: `Automatic`

This parameter configures the default value for the optional parameter `installPlanApproval` of the component library function `registerSubscription`.

== `defaultSourceNamespace`

[horizontal]
type:: string
default:: `openshift-marketplace`

This parameter configures the default value for the optional parameter `sourceNamespace` of the component library function `registerSubscription`.

== `defaultSource`

[horizontal]
type:: string
default::
+
* `community-operators` for instance `openshift-operators`
* `redhat-operators` for instance `openshift-operators-redhat`

This parameter configures the default value for the optional parameter `source` of the component library function `registerSubscription`.
