= Parameters

The parent key for all of the following parameters is `openshift4_operators`.

== `namespace`

[horizontal]
type:: string
default:: `${_instance}`

The namespace to create for the component instance.
The component is implemented in such a way that only instances (and therefore namespaces) `openshift-operators` and `openshift-operators-redhat` can be created, unless `useCustomNamespace` is set to `true`.
Generally, it shouldn't be necessary to override this parameter.

== `namespaceAnnotations`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
openshift.io/node-selector: ''
----

Annotations to be applied to the created namespace.
Annotations can be removed in the hierarchy by setting the value to `null`.

[NOTE]
====
Except for dropping null-valued entries, the component doesn't validate the provided annotations.
It's the user's responsibility to ensure that only valid annotations (both key and value must be strings) are provided.
====

== `defaultInstallPlanApproval`

[horizontal]
type:: string
default:: `Automatic`

This parameter configures the default value for the optional parameter `installPlanApproval` of the component library function `registerSubscription`.

== `defaultSourceNamespace`

[horizontal]
type:: string
default:: `openshift-marketplace`

This parameter configures the default value for the optional parameter `sourceNamespace` of the component library function `registerSubscription`.

== `defaultSource`

[horizontal]
type:: string
default::
+
* `certified-operators` for instance `openshift-operators`
* `redhat-operators` for instance `openshift-operators-redhat`

This parameter configures the default value for the optional parameter `source` of the component library function `registerSubscription`.

The component defaults to `certified-operators` for instance `openshift-operators`.
This source provides community-maintained operators which are certified by RedHat.
Alternatively, you can use `community-operators` for other community-maintained operators.

== `useCustomNamespace`

[horizontal]
type:: boolean
default:: `false`

Whether to allow non-standard namespace names for the OperatorGroup.
If this parameter is set to `true`, the component will allow using namespace names other than `openshift-operators` and `openshift-operators-redhat`.

== `subscription`

This parameter allows users of the component to configure one subscription per instance.
The component explicitly doesn't allow configuring multiple instances in the same namespace, since we've seen various issues with conflicting upgrades when multiple subscriptions are created in the same namespace, especially when `installPlanApproval=Manual` is required for some reason.
By default the components sets the nodeAffinity to infra nodes, this can be overwritten.
See https://docs.openshift.com/container-platform/latest/nodes/scheduling/nodes-scheduler-node-affinity.html#nodes-scheduler-node-affinity-configuring-required_nodes-scheduler-node-affinity[Official Documentation]

=== `subscription.name`

[horizontal]
type:: string
default:: `null`

The name of the operator to create a subscription for.
If this field isn't `null`, the component will create a `Subscription` object.

=== `subscription.channel`

[horizontal]
type:: string
default:: `null`

The name of the update channel to use for the subscription.

=== `subscription.spec`

[horizontal]
type:: object
default:: `{}`

This field is merged into the base `Subscription` object.
You can override any valid fields in the `Subscription` object's `spec` here.

IMPORTANT: The component doesn't validate the contents of this parameter.

== `operator_group`

This parameter allows users of the component to configure one OperatorGroup per instance.

== `operator_group.spec`
[horizontal]
type:: object
default:: `{}`

This field is merged into the base `OperatorGroup` object.
You can override any valid fields in the `OperatorGroup` object's `spec` here.

IMPORTANT: The component doesn't validate the contents of this parameter.
