= Parameters

The parent key for all of the following parameters is `openshift4_operators`.

== `namespace`

[horizontal]
type:: string
default:: `${_instance}`

The namespace to create for the component instance.
The component is implemented in such a way that only instances (and therefore namespaces) `openshift-operators` and `openshift-operators-redhat` can be created, unless `useCustomNamespace` is set to `true`.
Generally, it shouldn't be necessary to override this parameter.

== `namespaceAnnotations`

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
openshift.io/node-selector: node-role.kubernetes.io/infra=
----

Annotations to be applied to the created namespace.
Annotations can be removed in the hierarchy by setting the value to `null`.

[NOTE]
====
Except for dropping null-valued entries, the component doesn't validate the provided annotations.
It's the user's responsibility to ensure that only valid annotations (both key and value must be strings) are provided.
====

== `defaultInstallPlanApproval`

[horizontal]
type:: string
default:: `Automatic`

This parameter configures the default value for the optional parameter `installPlanApproval` of the component library function `registerSubscription`.

== `defaultSourceNamespace`

[horizontal]
type:: string
default:: `openshift-marketplace`

This parameter configures the default value for the optional parameter `sourceNamespace` of the component library function `registerSubscription`.

== `defaultSource`

[horizontal]
type:: string
default::
+
* `certified-operators` for instance `openshift-operators`
* `redhat-operators` for instance `openshift-operators-redhat`

This parameter configures the default value for the optional parameter `source` of the component library function `registerSubscription`.

The component defaults to `certified-operators` for instance `openshift-operators`.
This source provides community-maintained operators which are certified by RedHat.
Alternatively, you can use `community-operators` for other community-maintained operators.

== `useCustomNamespace`

[horizontal]
type:: boolean
default:: `false`

Whether to allow non-standard namespace names for the OperatorGroup.
If this parameter is set to `true`, the component will allow using namespace names other than `openshift-operators` and `openshift-operators-redhat`.

== `monitoring`

This parameter allows users to enable the component's monitoring configuration.
Currently the component has support for deploying custom `ServiceMonitors` on clusters which use component `prometheus` to manage a custom monitoring stack.

[WARNING]
The monitoring configuration is instance independent. It must not be changed between instances of this component.

=== `enabled`

[horizontal]
type:: boolean
default:: `true`

Whether to deploy monitoring configurations.
If this parameter is set to `true`, the component will check whether component `prometheus` is present on the cluster.
If the component is missing, no configurations will be deployed regardless of the value of this parameter.

=== `instance`

[horizontal]
type:: string
default:: `null`

This parameter can be used to indicate which custom Prometheus instance should pick up the configurations managed by the component.

If the parameter is set to the empty string, the default instance configured for component `prometheus` will be used.
